exclude: ^(blib2to3/|profiling/|tests/data/|\.mypy/|\.tox/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-case-conflict
      - id: check-json
        exclude: .vscode/settings.json
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: pretty-format-json
        exclude: .ipynb
        args:
          - --autofix
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        exclude: ^.venv/
        args: ["-S", "-l", "88"]
        name: black
        language: system
        entry: black
        types: [python]

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]

  - repo: https://github.com/timothycrosley/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          [
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--combine-as",
            "--line-length=88",
            "--thirdparty",
            "kedro",
          ]
        name: isort
        entry: isort
        require_serial: true
        language: python
        types: [python]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  #For checking on prints
  - repo: local
    hooks:
      - id: print_statement
        name: print statement
        types: [python]
        exclude: "^(migrations/|scripts/)"
        args: ["--multiline"]
        entry: 'print\('
        language: pygrep
